import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = __dirname;
const SOURCE_DIR = path.join(ROOT, 'dist');
const ICONS_DIR = path.join(ROOT, 'icons');
const BUILD_ROOT = path.join(ROOT, 'build');

const mode = process.argv[2] || 'development';
const envFile = mode === 'qa' ? '.env.qa' : '.env';
const envPath = path.join(ROOT, envFile);
const outputDir = path.join(BUILD_ROOT, mode);

function parseEnv(text) {
  const result = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function uniqueProviders(active, fallbacks) {
  return [active, ...fallbacks].filter(Boolean).filter((item, index, list) => list.indexOf(item) === index);
}

function json(value) {
  return JSON.stringify(value, null, 2);
}

async function copyDir(src, dest) {
  await fs.cp(src, dest, { recursive: true });
}

async function main() {
  const env = parseEnv(await fs.readFile(envPath, 'utf8'));
  const activeProvider = (env.TRANSCRIBE_PROVIDER || 'assemblyai').trim().toLowerCase();
  const fallbackProviders = uniqueProviders(
    activeProvider,
    (env.TRANSCRIBE_FALLBACKS || '').split(',').map((item) => item.trim().toLowerCase())
  );

  const config = {
    activeProvider,
    fallbackProviders,
    keys: {
      deepgram: env.DEEPGRAM_API_KEY || '',
      assemblyai: env.ASSEMBLYAI_API_KEY || '',
      openai: env.OPENAI_API_KEY || ''
    },
    deepgramModel: env.DEEPGRAM_MODEL || 'nova-3',
    assemblyaiModel: env.ASSEMBLYAI_MODEL || 'universal-3-5-pro',
    openaiModel: env.OPENAI_TRANSCRIBE_MODEL || 'gpt-4o-mini-transcribe',
    backendUrl: (env.BACKEND_URL || 'http://localhost:4000').replace(/\/$/, ''),
    clientUrl: (env.CLIENT_URL || env.BACKEND_URL || 'http://localhost:4000').replace(/\/$/, ''),
    buildEnvironment: mode
  };

  await fs.rm(outputDir, { recursive: true, force: true });
  await fs.mkdir(outputDir, { recursive: true });
  await copyDir(SOURCE_DIR, outputDir);
  await copyDir(ICONS_DIR, path.join(outputDir, 'icons'));

  // runtime-config.js is loaded by the extension pages that use module imports.
  const runtimeConfig = `// Generated by build.mjs from ${envFile}. Do not edit manually.\nglobalThis.AI_NOTE_CONFIG = ${json(config)};\n`;
  await fs.writeFile(path.join(outputDir, 'runtime-config.js'), runtimeConfig);

  // background.js is a classic MV3 service worker and intentionally embeds its config.
  const backgroundPath = path.join(outputDir, 'background.js');
  let background = await fs.readFile(backgroundPath, 'utf8');
  const configBlock = `globalThis.AI_NOTE_CONFIG = ${json(config)};`;
  const configStart = background.indexOf('globalThis.AI_NOTE_CONFIG = {');
  const configEnd = configStart >= 0 ? background.indexOf('};', configStart) : -1;
  if (configStart >= 0 && configEnd >= 0) {
    background = `${background.slice(0, configStart)}${configBlock}${background.slice(configEnd + 2)}`;
  } else {
    background = `${configBlock}\n\n${background}`;
  }
  await fs.writeFile(backgroundPath, background);

  // popup.html/popup.js still contain legacy fallback URLs. Keep them aligned with the build target.
  const legacyUrls = new Set([
    'http://localhost:4000',
    'http://localhost:3000',
    'http://192.168.1.5:4000',
    'http://192.168.1.5:3000'
  ]);
  const files = await fs.readdir(outputDir);
  for (const file of files) {
    if (!/\.(js|html|css)$/.test(file)) continue;
    const filePath = path.join(outputDir, file);
    let content = await fs.readFile(filePath, 'utf8');
    // Only replace legacy URL literals. API provider URLs are untouched.
    for (const oldUrl of legacyUrls) {
      const replacement = oldUrl.endsWith(':3000') ? config.clientUrl : config.backendUrl;
      content = content.split(oldUrl).join(replacement);
    }
    await fs.writeFile(filePath, content);
  }

  console.log(`Built ${mode} extension: ${path.relative(ROOT, outputDir)}`);
  console.log(`Backend URL: ${config.backendUrl}`);
  console.log(`Client URL:  ${config.clientUrl}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
