// Generated by build.mjs. Do not commit real API keys.
globalThis.AI_NOTE_CONFIG = {
  activeProvider: 'assemblyai',
  fallbackProviders: ['assemblyai', 'deepgram', 'openai'],
  keys: { deepgram: '', assemblyai: '', openai: '' },
  deepgramModel: 'nova-3',
  assemblyaiModel: 'universal-3-5-pro',
  openaiModel: 'gpt-4o-mini-transcribe'
};
